/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- */
/*
 * This file is part of the LibreOffice project.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */

#include <com/sun/star/lang/EventObject.idl>

module com {  module sun {  module star {  module awt {

/** describes a splitter drag event.

    @since LibreOffice 26.2
 */
published struct SplitEvent : com::sun::star::lang::EventObject
{
    /** the current split position in pixels. */
    long SplitPos;
};

}; }; }; };

/* vim:set shiftwidth=4 softtabstop=4 expandtab: */
